[project]
name = "test-task"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "black>=26.1.0",
    "flake8>=7.3.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "tabulate>=0.9.0",
]
